# Global Scratchpad Properties
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
scratchpad_cross_monitor=1

# Scratchpad Application Rules
windowrule=isnamedscratchpad:1,width:1800,height:1000,appid:thunderbird
windowrule=isnamedscratchpad:1,width:1800,height:1000,appid:obsidian

# Standard Window Rules
windowrule=appid:com.mitchellh.ghostty,focused_opacity:0.8,unfocused_opacity:0.6
